/**
 * WhatsApp bot: English & Swahili translations.
 * Use T(session, key) to get string for session.lang ('en' | 'sw').
 */

const L = {
  en: {
    // Home
    home_welcome: 'Welcome to',
    home_choose: 'Choose service:',
    home_type_zero: 'Type 0 anytime to go back here.',
    home_main_services: 'MAIN SERVICES',
    // Menu items
    menu_view: 'View Our Menu',
    menu_view_desc: 'View menu and order',
    rate_service: 'Rate Service',
    rate_desc: 'Give feedback',
    pay_bill: 'Pay Bill',
    pay_bill_desc: 'Pay your bill',
    tip: 'Tip',
    tip_desc: 'Tip the waiter',
    call_waiter: 'Call Waiter',
    call_waiter_desc: 'Request assistance',
    customer_support: 'Customer Support',
    customer_support_desc: 'Contact support',
    change_language: 'Change language',
    change_language_desc: 'Swahili / English',
    exit: 'Exit',
    exit_desc: 'Leave',
    // Language selection
    select_language: 'Select language:',
    lang_english: 'English',
    lang_swahili: 'Kiswahili',
    language_changed: 'Language set to English.',
    language_changed_sw: 'Lugha imewekwa kwa Kiswahili.',
    // Menu image
    downloading_menu: 'Downloading menu image...',
    here_is_menu: 'Here is our menu!',
    menu_type_order: 'Type your order (e.g. Chips 2, Soda 1) or type 0 to go back.',
    menu_commands: 'Commands:',
    menu_cmd_zero: '0 = Back to main menu',
    menu_cmd_order: 'Order = Type item name and quantity (e.g. Chips 2, Soda 1)',
    home_btn: 'Home (0)',
    menu_not_available: 'Sorry, menu image not available. Type 0 to go back.',
    // Pay bill / phone
    enter_phone_billed: 'Enter phone number to be billed',
    enter_phone_tip: 'Enter phone number to tip (e.g., 0712345678):',
    enter_phone_pay: 'Enter phone number to pay (e.g., 0712345678):',
    enter_amount: 'Enter amount to pay (Tsh):',
    tip_amount: 'Tip',
    invalid_number: 'Invalid number. Try again.',
    invalid_amount: 'Invalid amount. Enter numbers only.',
    sending_request: 'Sending payment request...',
    request_sent: 'Request sent to',
    confirm_on_phone: 'Please confirm on your phone.',
    bot_confirm_auto: 'TipTap will confirm automatically once payment is received.',
    // Customer support
    support_title: 'Customer Support',
    support_call: 'Call or WhatsApp:',
    support_type_zero: 'Type 0 to go back to main menu.',
    back_to_menu: 'Back to Menu',
    choose: 'Choose:',
    // General
    table: 'Table',
    goodbye: 'Goodbye! Thank you for visiting us.',
    processing_order: 'Processing your order...',
    order_received: 'Order Received!',
    order_id: 'Order #',
    items_found: 'Items found:',
    total: 'Total:',
    waiter_confirm: 'Waiter is coming to confirm...',
    pay_now: 'Pay Now',
    track_status: 'Track Status',
    home: 'Home',
    error_try_again: 'Technical error. Please try again.',
    error_order: 'We could not understand your order.',
    try_clear: 'Please try to type clearly (e.g., "Chips 2, Soda 1"). Type 0 to go back.',
    verifying: 'Verifying...',
    invalid_qr: 'Invalid QR Code or Tag.',
    enter_table: 'Enter table number (e.g., 7):',
    valid_table: 'Please enter a valid table number.',
    order_which_table: 'Which table are you at?',
    order_reply_table_number: 'Reply with the table number (e.g. 1, 2, 3).',
    thanks_feedback: 'Thanks for your feedback!',
    thanks_using_tiptap: 'Thanks for using TipTap!\n\nWelcome again! 👋',
    comment_prompt: 'Enter comment or type END to finish',
    not_understood: "Sorry, I didn't understand. Type \"Hi\" to start over.",
  },
  sw: {
    home_welcome: 'Karibu',
    home_choose: 'Chagua huduma:',
    home_type_zero: 'Andika 0 wakati wowote kurudi hapa.',
    home_main_services: 'HUDUMA ZA KUANZIA',
    menu_view: 'Tazama Menu',
    menu_view_desc: 'Tazama menu na kuagiza',
    rate_service: 'Kadiria Huduma',
    rate_desc: 'Toa maoni',
    pay_bill: 'Lipa Bili',
    pay_bill_desc: 'Lipa bili yako',
    tip: 'Mchango',
    tip_desc: 'Mpa mchango mhudumu',
    call_waiter: 'Mwalika Mhudumu',
    call_waiter_desc: 'Omba msaada',
    customer_support: 'Msaada wa Wateja',
    customer_support_desc: 'Wasiliana na msaada',
    change_language: 'Badilisha lugha',
    change_language_desc: 'Kiswahili / English',
    exit: 'Ondoka',
    exit_desc: 'Toka',
    select_language: 'Chagua lugha:',
    lang_english: 'English',
    lang_swahili: 'Kiswahili',
    language_changed: 'Language set to English.',
    language_changed_sw: 'Lugha imewekwa kwa Kiswahili.',
    downloading_menu: 'Inapakua picha ya menu...',
    here_is_menu: 'Hii ni menu yetu!',
    menu_type_order: 'Andika maagizo (mf. Chips 2, Soda 1) au andika 0 kurudi.',
    menu_commands: 'Maagizo:',
    menu_cmd_zero: '0 = Rudi kwenye menu kuu',
    menu_cmd_order: 'Agizo = Andika jina la kitu na idadi (mf. Chips 2, Soda 1)',
    home_btn: 'Nyumbani (0)',
    menu_not_available: 'Samahani, picha ya menu haipatikani. Andika 0 kurudi.',
    enter_phone_billed: 'Ingiza nambari ya simu ya kulipiwa',
    enter_phone_tip: 'Ingiza nambari ya simu ya mchango (mf. 0712345678):',
    enter_phone_pay: 'Ingiza nambari ya simu ya kulipa (mf. 0712345678):',
    enter_amount: 'Ingiza kiasi cha kulipa (Tsh):',
    tip_amount: 'Mchango',
    invalid_number: 'Nambari si sahihi. Jaribu tena.',
    invalid_amount: 'Kiasi si sahihi. Ingiza nambari tu.',
    sending_request: 'Inatumia ombi la malipo...',
    request_sent: 'Ombi limetumwa kwa',
    confirm_on_phone: 'Tafadhali thibitisha kwenye simu yako.',
    bot_confirm_auto: 'TipTap itathibitisha moja kwa moja malipo yanapopokelewa.',
    support_title: 'Msaada wa Wateja',
    support_call: 'Piga au WhatsApp:',
    support_type_zero: 'Andika 0 kurudi kwenye menu kuu.',
    back_to_menu: 'Rudi kwenye Menu',
    choose: 'Chagua:',
    table: 'Meza',
    goodbye: 'Kwaheri! Asante kwa kutembelea.',
    processing_order: 'Inachakata maagizo yako...',
    order_received: 'Agizo Limepokelewa!',
    order_id: 'Agizo #',
    items_found: 'Vitu vilivyopatikana:',
    total: 'Jumla:',
    waiter_confirm: 'Mhudumu anakuja kuthibitisha...',
    pay_now: 'Lipa Sasa',
    track_status: 'Ufuatiliaji',
    home: 'Nyumbani',
    error_try_again: 'Hitilafu ya kiufundi. Tafadhali jaribu tena.',
    error_order: 'Hatukuweza kuelewa agizo lako.',
    try_clear: 'Tafadhali andika wazi (mf. "Chips 2, Soda 1"). Andika 0 kurudi.',
    verifying: 'Inathibitisha...',
    invalid_qr: 'Msimbo wa QR au Tag si sahihi.',
    enter_table: 'Ingiza nambari ya meza (mf. 7):',
    valid_table: 'Tafadhali ingiza nambari sahihi ya meza.',
    order_which_table: 'Upo meza namba ngapi?',
    order_reply_table_number: 'Jibu kwa nambari ya meza (mf. 1, 2, 3).',
    thanks_feedback: 'Asante kwa maoni yako!',
    thanks_using_tiptap: 'Asante kwa kutumia TipTap!\n\nKaribu tena! 👋',
    comment_prompt: 'Ingiza maoni au andika END kumaliza',
    not_understood: 'Samahani, sikuweza kuelewa. Andika "Hi" kuanza.',
  },
};

function T(session, key) {
  const lang = session.lang || 'en';
  const s = L[lang] && L[lang][key];
  return s !== undefined ? s : (L.en[key] || key);
}

module.exports = { L, T };
